# Switch

JOY_BUTTON_SWITCH = 15

# Mouse

LEFT_AXIS = (0, 1)
RIGHT_AXIS = (2, 3)

JOY_BUTTON_LEFT_MOUSE_CLICK = 9
JOY_BUTTON_RIGHT_MOUSE_CLICK = 10
JOY_SCROLL_MODE = {'type': 'axis', 'value': 5}

# Keyboard

JOY_AXIS = (0, 1, 2, 3)

JOY_BUTTON_SPACE = 9
JOY_BUTTON_BACKSPACE = 10
JOY_SHIFT = {'type': 'axis', 'value': 4}
JOY_EXTENDED = {'type': 'axis', 'value': 5}
JOY_BUTTON_TAB = 7
JOY_BUTTON_RETURN = 8
JOY_BUTTON_CAPS_LOCK = 4
JOY_BUTTON_CMD = 2
JOY_BUTTON_OPTION = 1
JOY_BUTTON_CTRL = 3
JOY_BUTTON_ESC = 0
JOY_ARROWS = {'type': 'buttons', 'UP': 11, 'DOWN': 12, 'LEFT': 13, 'RIGHT': 14}
